name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "VITE_BASE_PATH=/NOM-DE-VOTRE-REPO/" >> $GITHUB_ENV
            echo "DEPLOY_FOLDER=." >> $GITHUB_ENV
          else
            echo "VITE_BASE_PATH=/NOM-DE-VOTRE-REPO/dev/" >> $GITHUB_ENV
            echo "DEPLOY_FOLDER=dev" >> $GITHUB_ENV
          fi

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          target-folder: ${{ env.DEPLOY_FOLDER }} 
          clean: ${{ github.ref == 'refs/heads/main' }}